### PR TITLE
Turbo PR

### PR DESCRIPTION
**Pull request by TurboProgramming**
Do not merge this until notice.

This is a PR to keep an eye to the changes that are going to be made to the `turbo` branch.

### CODE REVIEW

**Comment by PartialDevAdmin** [comment]
What does it to to the `.sideNav`?

**Comment by PartialDevAdmin** [comment]
I have updated it again, this changes the reply dropdowns and the follow dropdowns on a discussion page, gives them `padding: 3px;`

**Comment by PartialDevAdmin** [comment]
Updated to include an animation on the notification icon when the notification symbol appears, credit goes to [Pollux](https://discuss.flarum.org/u/Pollux), code is [here](https://discuss.flarum.org/d/13580-notification-bell-sound/5)

**Comment by PartialDevAdmin** [comment]
@TurboProgramming are you still working on this?

**Comment by TurboProgramming** [comment]
@PartialDevAdmin Definitely, just had some work to do I wasn't here a while. 

I'm going to be working a lot.

**Comment by PartialDevAdmin** [comment]
@TurboProgramming Ok!

**Comment by PartialDevAdmin** [comment]
@TurboProgramming just a heads up, this css is going to be put into an extension I am making. This is just the beginning :joy:

**Comment by TurboProgramming** [comment]
Should I add a visible divider between the all discussions, tags, following and the tags? It looks good.

**Comment by PartialDevAdmin** [comment]
Sure! Feel free to do whatever you want. I am totally open to suggestions!

**Comment by PartialDevAdmin** [comment]
Do the fontawesome icons look ok?

**Comment by TurboProgramming** [comment]
Let me do a review. One sec.

**Comment by TurboProgramming** [comment]
Where in the forum should I specifically check?

**Comment by PartialDevAdmin** [comment]
https://design.partialdev.com/d/1-applesauc, the Reply button above follow, and the Like and Reply buttons in the post

**Comment by PartialDevAdmin** [comment]
@TurboProgramming I activated your account on the forum and made you an admin

**Comment by PartialDevAdmin** [comment]
@TurboProgramming I just added a FA beside the scrubber bar on the discussions page, can you tell me what you think?

**Comment by PartialDevAdmin** [comment]
The changes are live on https://design.partialdev.com

**Comment by TurboProgramming** [comment]
The notification icon looks so cool!

**Comment by TurboProgramming** [comment]
But I didn't like the fact that you made the profile pics on discussion pages a bit more square, they looked way better when they were round circle.

**Comment by TurboProgramming** [comment]
screenshot_2018-07-25 applesauc - partialdev design

I don't have anything to say about this, it's OK maybe? If you'd ask me, I would've said you to remove it, but as we have icons and icons and icons everywhere, this may make sense, I don't know.

**Comment by TurboProgramming** [comment]
screenshot_2018-07-25 applesauc - partialdev design 1

The tag should be made round, to match up with other components.

**Comment by PartialDevAdmin** [comment]
@TurboProgramming thanks for the comments! I also can't decide about the icon beside the scrubber bar... i think for right now, i'll remove it. I'll also get that tag icon dealt with.

**Pull request merged**
